steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'functions',
        'deploy',
        'producer_function',
        '--entry-point',
        'producer',
        '--runtime',
        'nodejs12',
        '--trigger-http',
        '--allow-unauthenticated',
        '--memory=128MB',
        '--region=us-central1',
      ]
